version: "3.1"

services:
  weatherDB:
    image: mysql:latest
    container_name: weatherDb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .\data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weatherDB